name: base_flutter_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  chopper: ^7.2.0
  lazy_load_indexed_stack: ^1.1.0
  formz: ^0.7.0
  gap: ^3.0.1
  connectivity_plus: ^5.0.2
  dartx: ^1.2.0
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  injectable: 2.3.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  shimmer: ^3.0.0
  http_client_handler:
    path: packages/http_client_handler
  models:
    path: packages/models
  authentication_repository:
    path: packages/authentication_repository

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  chopper_generator: ^7.2.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/app/config/gen/
  line_length: 180

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/